name: Build Pages
on:
    workflow_dispatch:
    push:
        branches:
        - main  

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
            filters: |
                package:
                    - '{{cookiecutter.module_name}}/**'
                tests:
                    - 'tests/**'
 
      - name: Set up Python {{cookiecutter.python_version}}
        uses: actions/setup-python@v2
        with:
            python-version: {{cookiecutter.python_version}}
      - name: Build Pages
        if: {{"${{steps.filter.outputs.package == 'true' }}"}}
        run: |
            make init-docs
            make docs
        
      - name: Deploy Pages
        if: {{"${{steps.filter.outputs.package == 'true' }}"}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: {{"${{ secrets.GITHUB_TOKEN }}"}}
          publish_dir: ./docs/build/html 